x86_64-w64-mingw32: Compile OK. Link stop at DLL
Link stops when it needs to link to jtag_client.dll because the
we don't have the correct mangled C++ function name for jtag_client.dll

Other changes:
(1) added -lssp and get libjtag to compile with -fstack-protector-strong
in order to support better stack protection for minijtagserv. Without
this, you will get link error "undefined reference to '`__stack_chk_fail'"
(2) Endian decision is made by __BYTE_ORDER__ for gcc >4.6
(3) Whether it is Windows,Linux or Unix is now decided by autoconf, not
compiler option

Signed-off-by: U-GAR\cinlyooi <cinlyooi@cinlyooi-MOBL2.gar.corp.intel.com>